// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9a9_4gO_yp-a7xPNxUcQlJ-8JuBrEsA',
    appId: '1:851468764098:web:22605ce66a7374c1e00c5b',
    messagingSenderId: '851468764098',
    projectId: 'examap-9d534',
    authDomain: 'examap-9d534.firebaseapp.com',
    storageBucket: 'examap-9d534.appspot.com',
    measurementId: 'G-7QL159VHT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArvK327iCkwcgw75F7Uyi2s3aREL4pvpI',
    appId: '1:851468764098:android:508a1fdf6d2fed9ee00c5b',
    messagingSenderId: '851468764098',
    projectId: 'examap-9d534',
    storageBucket: 'examap-9d534.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu6zQk2Lb36Lprbf5fv2zdC6N5reklbII',
    appId: '1:851468764098:ios:4746dc25575cc4c2e00c5b',
    messagingSenderId: '851468764098',
    projectId: 'examap-9d534',
    storageBucket: 'examap-9d534.appspot.com',
    iosClientId: '851468764098-ol25p2ii8mn3adabrrqp532mm097r7u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.examap',
  );
}
